export const productTags = [
  "Headphones",
  "Laptop",
  "Mobile",
  "Tablet",
  "Sneakers",
  "Alexa",
  "Oppo",
  "Speakers",
];

export const products = [
  {
    id: 1,
    image: "/images/prod1.jpg",
    brand: "Apple",
    title: "Apple - AirPods Max",
    rating: 4.8,
    description:
      "The AirPods Max bring the magic of AirPods to a stunning over-ear design with high-fidelity audio, Active Noise Cancellation, and spatial audio. Experience the ultimate personal listening experience with custom-built drivers that deliver deep bass, accurate mids, and crisp highs. The breathable knit mesh canopy and memory foam ear cushions provide an exceptional fit for all-day comfort. Advanced software tailors the sound to the geometry of your ear for a rich, consistent listening experience. With up to 20 hours of high-fidelity audio, talk time, or movie playback, you'll never be without your favorite sounds.",
    price: "$ 529.99",
    link: "/product-1",
    categories: ["Electronics", "Apple Products", "Gadgets", "Lifestyle"],
    tags: [
      "Apple",
      "AirPods",
      "Wireless Earbuds",
      "Bluetooth",
      "Noise Cancellation",
    ],
    availability: "125 in Stock",
    SKU: "542",
    reviews: "(221 Reviews)",
    reviewers: [
      {
        name: "John Doe",
        rating: 5,
        comment: "Amazing sound quality and very comfortable to wear!",
      },
      {
        name: "Jane Smith",
        rating: 4,
        comment: "Great headphones but a bit pricey.",
      },
    ],
    images: [
      "/images/prod01.jpg",
      "/images/prod-11.jpg",
      "/images/prod-111.jpg",
      "/images/prod-1.jpg",
    ],
    sizes: ["One Size"],
    colorCount: 4,
    count: 125,
  },
  {
    id: 2,
    image: "/images/prod-2.jpg",
    brand: "Jazwares",
    title: 'Squishmallows 16" Plush - Holiday Cat in Blue Scarf',
    rating: 4.5,
    description:
      "Celebrate the holidays with the adorable Squishmallows Holiday Cat. This 16-inch plush toy is perfect for cuddling and brings festive cheer with its cute blue scarf. Made with soft, high-quality materials, it's a great gift for kids and collectors alike. The Squishmallows Holiday Cat is incredibly soft and squeezable, providing a delightful tactile experience. It's durable enough for playtime, yet gentle enough to be a bedtime companion. Add this charming plush to your collection and spread some holiday joy.",
    price: "$ 24.99",
    link: "/product-2",
    categories: ["Toys & Games", "Holiday", "Gifts"],
    tags: ["Squishmallows", "Plush Toy", "Holiday", "Cat", "Blue Scarf"],
    availability: "32 in Stock",
    SKU: "721",
    reviews: "(421 Reviews)",
    reviewers: [
      {
        name: "Emily Johnson",
        rating: 5,
        comment: "Absolutely adorable and so soft!",
      },
      {
        name: "Michael Brown",
        rating: 4,
        comment: "My kids love it, perfect for the holidays.",
      },
    ],
    images: [
      "/images/prod-2.jpg",
      "/images/prod-22.jpg",
      "/images/prod-222.jpg",
      "/images/prod-2222.jpg",
    ],
    sizes: ["S", "M", "L", "XXL"],
    colorCount: 4,
    count: 32,
  },
  {
    id: 3,
    image: "/images/prod-3.jpg",
    brand: "Sonos",
    title: "Sonos Move 2 Speaker",
    rating: 3.5,
    description:
      "The Sonos Move 2 is the durable, battery-powered smart speaker for outdoor and indoor listening. With Wi-Fi and Bluetooth connectivity, it provides brilliant sound anywhere. Enjoy deep bass, a wide soundscape, and automatic Trueplay tuning that adjusts the sound for the space you're in. The Move 2's weather-resistant design and long-lasting battery make it perfect for outdoor adventures, while its rich, powerful sound fills any room when you're at home. Stream music, radio, audiobooks, and more from your favorite services, and control it all with your voice, the Sonos app, and Apple AirPlay 2.",
    price: "$ 449.00",
    link: "/product-3",
    categories: ["Electronics", "Audio Devices", "Portable Speakers"],
    tags: ["Sonos", "Move 2", "Smart Speaker", "Bluetooth", "Portable"],
    availability: "75 in Stock",
    SKU: "938",
    reviews: "(901 Reviews)",
    reviewers: [
      {
        name: "Sarah Davis",
        rating: 4,
        comment: "Great sound quality, but a bit heavy to carry around.",
      },
      {
        name: "David Wilson",
        rating: 3,
        comment: "Good speaker but the battery life could be better.",
      },
    ],
    images: [
      "/images/prod-3.jpg",
      "/images/prod-333.jpg",
      "/images/prod-33.jpg",
      "/images/prod-3333.jpg",
    ],
    sizes: ["One Size"],
    colorCount: 3,
    count: 75,
  },
  {
    id: 4,
    image: "/images/prod-4.jpg",
    brand: "PELONIS",
    title: "42-Inch Tower Fan, Standing Fan with Remote",
    rating: 3,
    description:
      "Stay cool with the PELONIS 42-Inch Tower Fan. This standing fan features three speed settings, oscillation, and a convenient remote control. Its sleek, space-saving design fits perfectly in any room while providing powerful and quiet airflow for a comfortable environment. The fan's wide-angle oscillation ensures even air distribution, while the timer function allows you to set it to turn off automatically after a specified period. The easy-to-use control panel and remote control offer convenient operation, making this fan a great addition to your home or office.",
    price: "$ 79.99",
    link: "/product-4",
    categories: ["Home Appliances", "Cooling Devices", "Fans"],
    tags: ["PELONIS", "Tower Fan", "Standing Fan", "Remote Control", "Cooling"],
    availability: "60 in Stock",
    SKU: "117",
    reviews: "(11 Reviews)",
    reviewers: [
      {
        name: "Chris Martinez",
        rating: 3,
        comment: "Works well but a bit noisy at the highest setting.",
      },
      {
        name: "Amanda Anderson",
        rating: 3,
        comment: "Decent fan, but the remote control could be more responsive.",
      },
    ],
    images: [
      "/images/prod-04.jpg",
      "/images/prod-44.jpg",
      "/images/prod-444.jpg",
      "/images/prod-4444.jpg",
    ],
    sizes: ["One Size"],
    colorCount: 1,
    count: 60,
  },
  {
    id: 5,
    image: "/images/prod-5.jpg",
    brand: "Sony",
    title: "PlayStation 5 DualSense Wireless Controller",
    rating: 4.5,
    description:
      "The PlayStation 5 DualSense Wireless Controller offers immersive haptic feedback, dynamic adaptive triggers, and a built-in microphone, all integrated into an iconic comfortable design. Elevate your gaming experience with intuitive control and a deep sense of connectivity. The DualSense controller also features a built-in rechargeable battery, a strong, durable build, and an ergonomic grip for long gaming sessions. Compatible with a variety of PlayStation 5 games, this controller provides a truly immersive experience with its responsive triggers and detailed haptic feedback.",
    price: "$ 69.00",
    link: "/product-5",
    categories: ["Electronics", "Gaming", "Accessories"],
    tags: [
      "Sony",
      "PlayStation 5",
      "DualSense",
      "Wireless Controller",
      "Gaming",
    ],
    availability: "32 in Stock",
    SKU: "401",
    reviews: "(6721 Reviews)",
    reviewers: [
      {
        name: "Jessica Lee",
        rating: 5,
        comment: "Best controller I've ever used, super responsive!",
      },
      {
        name: "Daniel White",
        rating: 4,
        comment: "Great controller but the battery life could be longer.",
      },
    ],
    images: [
      "/images/prod-05.jpg",
      "/images/prod-55.jpg",
      "/images/prod-555.jpg",
      "/images/prod-5555.jpg",
    ],
    sizes: ["One Size"],
    colorCount: 4,
    count: 32,
  },
  {
    id: 6,
    image: "/images/prod-6.jpg",
    brand: "Samsung",
    title: "Samsung Galaxy Watch 6",
    rating: 4.4,
    description:
      "The Samsung Galaxy Watch6 is your perfect health and fitness companion. Track your workouts, heart rate, and sleep patterns with this sleek and stylish smartwatch. With a bright display and long battery life, stay connected and in control all day long. The Galaxy Watch6 offers advanced health monitoring features, including ECG and blood oxygen levels, as well as a variety of fitness tracking options. Its durable, water-resistant design makes it ideal for all-day wear, whether you're at the gym, at work, or out on the town. Stay in touch with notifications, calls, and messages right from your wrist.",
    price: "$ 209",
    link: "/product-6",
    categories: ["Electronics", "Wearable Technology", "Smartwatches"],
    tags: [
      "Samsung",
      "Galaxy Watch6",
      "Smartwatch",
      "Fitness Tracker",
      "Health Monitor",
    ],
    availability: "100 in Stock",
    SKU: "856",
    reviews: "(501 Reviews)",
    reviewers: [
      {
        name: "Megan Green",
        rating: 5,
        comment: "Love this watch! Great for tracking my workouts.",
      },
      {
        name: "Brian Hall",
        rating: 4,
        comment: "Very functional but a bit pricey.",
      },
    ],
    images: [
      "/images/prod06.jpg",
      "/images/prod-66.jpg",
      "/images/prod-666.jpg",
      "/images/prod-6666.jpg",
    ],
    sizes: ["S", "M", "L", "XL"],
    colorCount: 3,
    count: 100,
  },
];
